---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-permissions
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "project.openshift.io"
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "mcpserver.opendatahub.io"
    resources:
      - mcpservers
    verbs:
      - get
      - list
      - watch