# This rule is not used by the project mcp-server-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mcpserver.opendatahub.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcp-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-viewer-role
rules:
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers/status
  verbs:
  - get
